<?php
/**
 * Plugin Name: BZJ Connections Synchronization Control Plane
 * Description: Buzzjuice Network relationship control plane. BuddyBoss/WordPress is the canonical authority; Streams and Socials are projections and signed synchronization clients.
 * Version: 8.3.0
 * Author: Buzzjuice
 * Requires at least: 6.0
 * Requires PHP: 7.4
 */
defined('ABSPATH') || exit;
if (defined('BZJ_CONNECTIONS_SYNC_LOADED')) return;
define('BZJ_CONNECTIONS_SYNC_LOADED', true);

final class BZJ_Connections_Sync {
    const VERSION='8.3.0';
    const NS='bzj/v6'; const ROUTE='/connection-management';
    const LEDGER='bzj_relationships'; const EVENTS='bzj_relationship_events';
    const LOG_DIR='/data/logs'; const LOG_FILE='bzj-connections-sync.log';
    const LOCK_TIMEOUT=15; const TIMESTAMP_WINDOW=300; const MAX_ATTEMPTS=8; const CRON='bzj_connections_sync_recovery';
    const WP='wordpress'; const STREAMS='streams'; const SOCIALS='socials';
    const REQUEST='connection_request'; const ACCEPT='connection_accept'; const REJECT='connection_reject'; const WITHDRAW='connection_withdraw'; const REMOVE='connection_remove';
    const FOLLOW='follow'; const UNFOLLOW='unfollow'; const BLOCK='block'; const UNBLOCK='unblock';
    private static $instance; private $ledger_table; private $events_table; private $context=array(); private $locks=array();

    public static function instance(){ return self::$instance ?: (self::$instance=new self()); }
    private function __construct(){
        global $wpdb;
        $this->ledger_table=$wpdb->prefix.self::LEDGER; $this->events_table=$wpdb->prefix.self::EVENTS;
        add_action('rest_api_init',array($this,'register_routes'));
        add_action('friends_friendship_requested',array($this,'bb_requested'),20,4);
        add_action('friends_friendship_accepted',array($this,'bb_accepted'),20,4);
        add_action('friends_friendship_rejected',array($this,'bb_rejected'),20,2);
        add_action('friends_friendship_withdrawn',array($this,'bb_withdrawn'),20,2);
        add_action('friends_friendship_deleted',array($this,'bb_deleted'),5,3);
        add_action('friends_friendship_post_delete',array($this,'bb_post_deleted'),20,2);
        add_action('bp_start_following',array($this,'bb_follow_started'),20,1);
        add_action('bp_stop_following',array($this,'bb_follow_stopped'),20,1);
        add_action('bp_moderation_after_save',array($this,'bb_moderation_saved'),20,1);
        add_action('bb_moderation_after_delete',array($this,'bb_moderation_deleted'),20,1);
        add_filter('cron_schedules',array($this,'cron_schedules'));
        add_action(self::CRON,array($this,'process_recovery'));
        $this->install_schema(); $this->schedule();
    }
    public function cron_schedules($s){ if(empty($s['bzj_five_minutes'])) $s['bzj_five_minutes']=array('interval'=>300,'display'=>'BZJ every five minutes'); return $s; }
    private function schedule(){ if(!wp_next_scheduled(self::CRON)) wp_schedule_event(time()+60,'bzj_five_minutes',self::CRON); }
    private function log($message,$context=array()){
        $dir=trailingslashit(ABSPATH).ltrim(self::LOG_DIR,'/'); if(!is_dir($dir)) wp_mkdir_p($dir); if(!is_dir($dir)||!is_writable($dir)) return false;
        return false!==@file_put_contents(trailingslashit($dir).self::LOG_FILE,wp_json_encode(array('time'=>gmdate('c'),'message'=>(string)$message,'context'=>$context),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).PHP_EOL,FILE_APPEND|LOCK_EX);
    }
    private function install_schema(){
        $v=get_option('bzj_connections_sync_schema_version',''); if($v===self::VERSION) return;
        require_once ABSPATH.'wp-admin/includes/upgrade.php'; global $wpdb; $c=$wpdb->get_charset_collate();
        $sql1="CREATE TABLE {$this->ledger_table} (
            id bigint(20) unsigned NOT NULL AUTO_INCREMENT,user_a bigint(20) unsigned NOT NULL,user_b bigint(20) unsigned NOT NULL,
            connection_state varchar(20) NOT NULL DEFAULT 'none',requested_by bigint(20) unsigned NOT NULL DEFAULT 0,
            follow_a_to_b tinyint(1) unsigned NOT NULL DEFAULT 0,follow_b_to_a tinyint(1) unsigned NOT NULL DEFAULT 0,
            socials_follow_a_to_b tinyint(1) unsigned NOT NULL DEFAULT 0,socials_follow_b_to_a tinyint(1) unsigned NOT NULL DEFAULT 0,
            block_a_to_b tinyint(1) unsigned NOT NULL DEFAULT 0,block_b_to_a tinyint(1) unsigned NOT NULL DEFAULT 0,
            version bigint(20) unsigned NOT NULL DEFAULT 1,last_event_uuid char(36) NOT NULL DEFAULT '',created_at datetime NOT NULL,updated_at datetime NOT NULL,
            PRIMARY KEY(id),UNIQUE KEY user_pair(user_a,user_b),KEY updated_at(updated_at),KEY connection_state(connection_state)
        ) $c;";
        $sql2="CREATE TABLE {$this->events_table} (
            id bigint(20) unsigned NOT NULL AUTO_INCREMENT,event_uuid char(36) NOT NULL,origin varchar(20) NOT NULL,operation varchar(40) NOT NULL,
            actor_wp_id bigint(20) unsigned NOT NULL DEFAULT 0,target_wp_id bigint(20) unsigned NOT NULL DEFAULT 0,pair_a bigint(20) unsigned NOT NULL DEFAULT 0,pair_b bigint(20) unsigned NOT NULL DEFAULT 0,
            payload longtext NULL,status varchar(20) NOT NULL DEFAULT 'pending',attempts int(10) unsigned NOT NULL DEFAULT 0,next_attempt_at datetime NOT NULL,last_error text NULL,processed_at datetime NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,
            PRIMARY KEY(id),UNIQUE KEY event_uuid(event_uuid),KEY queue(status,next_attempt_at),KEY pair_key(pair_a,pair_b)
        ) $c;";
        dbDelta($sql1); dbDelta($sql2); update_option('bzj_connections_sync_schema_version',self::VERSION,false);
        if(!empty($wpdb->last_error)) $this->log('Schema installation error',array('error'=>$wpdb->last_error)); else $this->log('Schema ready',array('ledger'=>$this->ledger_table,'events'=>$this->events_table));
    }
    private function pair($a,$b){$a=absint($a);$b=absint($b);return $a<$b?array($a,$b):array($b,$a);}
    private function lock_name($a,$b){$p=$this->pair($a,$b);return 'bzj_pair_'.$p[0].'_'.$p[1];}
    private function lock($a,$b){global $wpdb;$n=$this->lock_name($a,$b);if(isset($this->locks[$n])){$this->locks[$n]++;return true;} $r=$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s,%d)',$n,self::LOCK_TIMEOUT));if((int)$r!==1)return false;$this->locks[$n]=1;return true;}
    private function unlock($a,$b){global $wpdb;$n=$this->lock_name($a,$b);if(!isset($this->locks[$n]))return;$this->locks[$n]--;if($this->locks[$n]<=0){unset($this->locks[$n]);$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$n));}}
    private function push(){ $this->context[]=1; } private function pop(){array_pop($this->context);} private function internal(){return !empty($this->context);}
    private function uuid($v){return (bool)preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',(string)$v);}
    private function ledger($a,$b){global $wpdb;$p=$this->pair($a,$b);$r=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->ledger_table} WHERE user_a=%d AND user_b=%d LIMIT 1",$p[0],$p[1]),ARRAY_A);return $r?:array('user_a'=>$p[0],'user_b'=>$p[1],'connection_state'=>'none','requested_by'=>0,'follow_a_to_b'=>0,'follow_b_to_a'=>0,'socials_follow_a_to_b'=>0,'socials_follow_b_to_a'=>0,'block_a_to_b'=>0,'block_b_to_a'=>0,'version'=>0,'last_event_uuid'=>'');}
    private function save_ledger($a,$b,$changes,$uuid=''){
        global $wpdb;$p=$this->pair($a,$b);$old=$this->ledger($a,$b);$now=gmdate('Y-m-d H:i:s');
        $data=array('user_a'=>$p[0],'user_b'=>$p[1],'connection_state'=>isset($changes['connection_state'])?sanitize_key($changes['connection_state']):$old['connection_state'],'requested_by'=>isset($changes['requested_by'])?absint($changes['requested_by']):absint($old['requested_by']),'follow_a_to_b'=>isset($changes['follow_a_to_b'])?(int)(bool)$changes['follow_a_to_b']:(int)$old['follow_a_to_b'],'follow_b_to_a'=>isset($changes['follow_b_to_a'])?(int)(bool)$changes['follow_b_to_a']:(int)$old['follow_b_to_a'],'socials_follow_a_to_b'=>isset($changes['socials_follow_a_to_b'])?(int)(bool)$changes['socials_follow_a_to_b']:(int)$old['socials_follow_a_to_b'],'socials_follow_b_to_a'=>isset($changes['socials_follow_b_to_a'])?(int)(bool)$changes['socials_follow_b_to_a']:(int)$old['socials_follow_b_to_a'],'block_a_to_b'=>isset($changes['block_a_to_b'])?(int)(bool)$changes['block_a_to_b']:(int)$old['block_a_to_b'],'block_b_to_a'=>isset($changes['block_b_to_a'])?(int)(bool)$changes['block_b_to_a']:(int)$old['block_b_to_a'],'version'=>max(1,(int)$old['version']+1),'last_event_uuid'=>$uuid?:$old['last_event_uuid'],'updated_at'=>$now);
        if(empty($old['id'])){$data['created_at']=$now;$ok=$wpdb->insert($this->ledger_table,$data);}else{$ok=$wpdb->update($this->ledger_table,$data,array('id'=>(int)$old['id']));}
        if(false===$ok)throw new RuntimeException('Ledger write failed: '.$wpdb->last_error);return $this->ledger($a,$b);
    }
    private function event_exists($uuid){global $wpdb;return (bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$this->events_table} WHERE event_uuid=%s LIMIT 1",$uuid));}
    private function event_status($uuid){global $wpdb;return (string)$wpdb->get_var($wpdb->prepare("SELECT status FROM {$this->events_table} WHERE event_uuid=%s LIMIT 1",$uuid));}
    private function create_event($uuid,$origin,$op,$a,$b,$payload=array()){
        global $wpdb;if($this->event_exists($uuid))return true;$p=$this->pair($a,$b);$now=gmdate('Y-m-d H:i:s');$ok=$wpdb->insert($this->events_table,array('event_uuid'=>$uuid,'origin'=>sanitize_key($origin),'operation'=>sanitize_key($op),'actor_wp_id'=>absint($a),'target_wp_id'=>absint($b),'pair_a'=>$p[0],'pair_b'=>$p[1],'payload'=>wp_json_encode($payload),'status'=>'pending','attempts'=>0,'next_attempt_at'=>$now,'created_at'=>$now,'updated_at'=>$now));if(false===$ok)throw new RuntimeException('Event insert failed: '.$wpdb->last_error);return true;
    }
    private function processed($uuid){global $wpdb;$wpdb->update($this->events_table,array('status'=>'processed','processed_at'=>gmdate('Y-m-d H:i:s'),'updated_at'=>gmdate('Y-m-d H:i:s'),'last_error'=>null),array('event_uuid'=>$uuid));}
    private function retry($uuid,$error){global $wpdb;$n=(int)$wpdb->get_var($wpdb->prepare("SELECT attempts FROM {$this->events_table} WHERE event_uuid=%s LIMIT 1",$uuid))+1;$status=$n>=self::MAX_ATTEMPTS?'failed':'pending';$delay=min(3600,max(60,pow(2,min(10,$n))));$wpdb->update($this->events_table,array('status'=>$status,'attempts'=>$n,'next_attempt_at'=>gmdate('Y-m-d H:i:s',time()+$delay),'last_error'=>substr((string)$error,0,65000),'updated_at'=>gmdate('Y-m-d H:i:s')),array('event_uuid'=>$uuid));}
    private function mapping($wp,$platform){return absint(get_user_meta(absint($wp),$platform===self::STREAMS?'wo_user_id':'qd_user_id',true));}
    private function wp_from_external($platform,$ext){global $wpdb;$key=$platform===self::STREAMS?'wo_user_id':'qd_user_id';return (int)$wpdb->get_var($wpdb->prepare("SELECT user_id FROM {$wpdb->usermeta} WHERE meta_key=%s AND meta_value=%s ORDER BY umeta_id ASC LIMIT 1",$key,(string)absint($ext)));}
    private function load_helpers(){static $loaded=false;if($loaded)return true;$paths=array(ABSPATH.'shared/db_helpers.php',dirname(ABSPATH).'/shared/db_helpers.php');foreach($paths as $p){if(is_file($p)){require_once $p;$loaded=true;return true;}}$this->log('db_helpers.php missing',array('paths'=>$paths));return false;}
    private function db($platform){if(!$this->load_helpers())return false;$fn=$platform===self::STREAMS?'get_wowonder_db':'get_qd_db_conn';if(!function_exists($fn))return false;$db=$fn();return $db instanceof mysqli?$db:false;}
    private function table($db,$platform,$kind){$names=$kind==='follow'?($platform===self::STREAMS?array('Wo_Followers','wo_followers','followers'):array('followers')):($platform===self::STREAMS?array('Wo_Blocks','wo_blocks','blocks'):array('blocks'));foreach($names as $t){$q=$db->query("SHOW TABLES LIKE '".$db->real_escape_string($t)."'");if($q instanceof mysqli_result&&$q->num_rows){$q->free();return $t;}}return false;}
    private function columns($db,$table){$o=array();$t=preg_replace('/[^A-Za-z0-9_]/','',$table);$q=$db->query("SHOW COLUMNS FROM `{$t}`");if($q)while($r=$q->fetch_assoc())$o[strtolower($r['Field'])]=true;return $o;}
    private function ext_follow_upsert($platform,$a,$b,$active){$ea=$this->mapping($a,$platform);$eb=$this->mapping($b,$platform);if(!$ea||!$eb)throw new RuntimeException($platform.' user mapping missing');$db=$this->db($platform);if(!$db)throw new RuntimeException($platform.' database unavailable');$t=$this->table($db,$platform,'follow');if(!$t)throw new RuntimeException($platform.' followers table missing');$s=$db->prepare("SELECT id FROM `{$t}` WHERE following_id=? AND follower_id=? LIMIT 1");if(!$s)throw new RuntimeException($db->error);$s->bind_param('ii',$eb,$ea);$s->execute();$r=$s->get_result();$row=$r?$r->fetch_assoc():null;$s->close();if($row){$id=(int)$row['id'];$s=$db->prepare("UPDATE `{$t}` SET active=? WHERE id=?");$s->bind_param('ii',$active,$id);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}else{$c=$this->columns($db,$t);if(isset($c['created_at'])){$now=time();$s=$db->prepare("INSERT INTO `{$t}` (following_id,follower_id,active,created_at) VALUES (?,?,?,?)");$s->bind_param('iiii',$eb,$ea,$active,$now);}elseif(isset($c['time'])){$now=time();$s=$db->prepare("INSERT INTO `{$t}` (following_id,follower_id,active,time) VALUES (?,?,?,?)");$s->bind_param('iiii',$eb,$ea,$active,$now);}else{$s=$db->prepare("INSERT INTO `{$t}` (following_id,follower_id,active) VALUES (?,?,?)");$s->bind_param('iii',$eb,$ea,$active);}if(!$s||!$s->execute())throw new RuntimeException($db->error);$s->close();}$this->verify_follow($platform,$a,$b,$active);}
    private function ext_follow_delete($platform,$a,$b){$ea=$this->mapping($a,$platform);$eb=$this->mapping($b,$platform);if(!$ea||!$eb)throw new RuntimeException($platform.' user mapping missing');$db=$this->db($platform);if(!$db)throw new RuntimeException($platform.' database unavailable');$t=$this->table($db,$platform,'follow');if(!$t)throw new RuntimeException($platform.' followers table missing');$s=$db->prepare("DELETE FROM `{$t}` WHERE following_id=? AND follower_id=?");$s->bind_param('ii',$eb,$ea);if(!$s->execute())throw new RuntimeException($s->error);$s->close();$this->verify_follow($platform,$a,$b,0);}
    private function verify_follow($platform,$a,$b,$active){$ea=$this->mapping($a,$platform);$eb=$this->mapping($b,$platform);$db=$this->db($platform);$t=$this->table($db,$platform,'follow');$s=$db->prepare("SELECT active FROM `{$t}` WHERE following_id=? AND follower_id=? LIMIT 1");$s->bind_param('ii',$eb,$ea);$s->execute();$r=$s->get_result();$row=$r?$r->fetch_assoc():null;$s->close();$actual=$row?(int)$row['active']:0;if($actual!==(int)$active)throw new RuntimeException($platform.' follow verification failed');}
    private function ext_block($platform,$a,$b,$active){$ea=$this->mapping($a,$platform);$eb=$this->mapping($b,$platform);if(!$ea||!$eb)throw new RuntimeException($platform.' user mapping missing');$db=$this->db($platform);if(!$db)throw new RuntimeException($platform.' database unavailable');$t=$this->table($db,$platform,'block');if(!$t)throw new RuntimeException($platform.' blocks table missing');if($platform===self::STREAMS)$where='blocker=? AND blocked=?';else$where='user_id=? AND block_userid=?';if($active){$s=$db->prepare("SELECT id FROM `{$t}` WHERE {$where} LIMIT 1");$s->bind_param('ii',$ea,$eb);$s->execute();$r=$s->get_result();$exists=$r&&$r->fetch_assoc();$s->close();if(!$exists){if($platform===self::STREAMS)$s=$db->prepare("INSERT INTO `{$t}` (blocker,blocked) VALUES (?,?)");else{$now=gmdate('Y-m-d H:i:s');$s=$db->prepare("INSERT INTO `{$t}` (user_id,block_userid,created_at) VALUES (?,?,?)");$s->bind_param('iis',$ea,$eb,$now);}if($platform===self::STREAMS)$s->bind_param('ii',$ea,$eb);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}}else{$s=$db->prepare("DELETE FROM `{$t}` WHERE {$where}");$s->bind_param('ii',$ea,$eb);if(!$s->execute())throw new RuntimeException($s->error);$s->close();}$this->verify_block($platform,$a,$b,$active);if($active)$this->ext_follow_delete($platform,$a,$b);}
    private function verify_block($platform,$a,$b,$active){$ea=$this->mapping($a,$platform);$eb=$this->mapping($b,$platform);$db=$this->db($platform);$t=$this->table($db,$platform,'block');$sql=$platform===self::STREAMS?"SELECT id FROM `{$t}` WHERE blocker=? AND blocked=? LIMIT 1":"SELECT id FROM `{$t}` WHERE user_id=? AND block_userid=? LIMIT 1";$s=$db->prepare($sql);$s->bind_param('ii',$ea,$eb);$s->execute();$r=$s->get_result();$exists=$r&&$r->fetch_assoc();$s->close();if((bool)$exists!==((bool)$active))throw new RuntimeException($platform.' block verification failed');}
    private function bb_status($a,$b){return function_exists('friends_check_friendship_status')?friends_check_friendship_status($a,$b):'not_friends';}
    private function bb_blocked($a,$b){if($this->bb_block_dir($a,$b)||$this->bb_block_dir($b,$a))return true;return false;}
    private function bb_block_dir($a,$b){if(!class_exists('BP_Moderation')||!class_exists('BP_Moderation_Members'))return false;$m=new BP_Moderation($b,BP_Moderation_Members::$moderation_type,$a);return !empty($m->id)&&empty($m->user_report);}
    private function refresh_ledger($a,$b,$uuid=''){
        $p=$this->pair($a,$b);$l=$this->ledger($a,$b);$changes=array('connection_state'=>'none','requested_by'=>0,'follow_a_to_b'=>function_exists('bp_is_following')&&bp_is_following(array('leader_id'=>$b,'follower_id'=>$a))?1:0,'follow_b_to_a'=>function_exists('bp_is_following')&&bp_is_following(array('leader_id'=>$a,'follower_id'=>$b))?1:0,'block_a_to_b'=>$this->bb_block_dir($p[0],$p[1])?1:0,'block_b_to_a'=>$this->bb_block_dir($p[1],$p[0])?1:0);
        $st=$this->bb_status($a,$b);if($st==='is_friend')$changes['connection_state']='connected';elseif($st==='pending'){$changes['connection_state']='requested';$changes['requested_by']=$a;}elseif($st==='awaiting_response'){$changes['connection_state']='requested';$changes['requested_by']=$b;}
        if($changes['block_a_to_b']||$changes['block_b_to_a']){$changes['connection_state']='none';$changes['requested_by']=0;$changes['follow_a_to_b']=0;$changes['follow_b_to_a']=0;}
        foreach(array('socials_follow_a_to_b','socials_follow_b_to_a') as $k)if(!isset($changes[$k]))$changes[$k]=isset($l[$k])?(int)$l[$k]:0;
        return $this->save_ledger($p[0],$p[1],$changes,$uuid);
    }
    private function qd_desired($a,$b){$l=$this->ledger($a,$b);$p=$this->pair($a,$b);$dir=$a===$p[0]?'socials_follow_a_to_b':'socials_follow_b_to_a';if($l['connection_state']==='requested'){return $a===(int)$l['requested_by']?0:0;}if($l['connection_state']==='connected')return 1;return !empty($l[$dir])?1:0;}
    private function qd_project($a,$b){$l=$this->ledger($a,$b);$p=$this->pair($a,$b);$dir=$a===$p[0]?'socials_follow_a_to_b':'socials_follow_b_to_a';if($l['connection_state']==='requested'){$requester=(int)$l['requested_by'];if($requester===$a)$this->ext_follow_upsert(self::SOCIALS,$a,$b,0);else $this->ext_follow_delete(self::SOCIALS,$a,$b);return;}if($l['connection_state']==='connected'){$this->ext_follow_upsert(self::SOCIALS,$a,$b,1);return;}if(!empty($l[$dir]))$this->ext_follow_upsert(self::SOCIALS,$a,$b,1);else $this->ext_follow_delete(self::SOCIALS,$a,$b);}
    private function project_socials($a,$b){$this->qd_project($a,$b);$this->qd_project($b,$a);}
    private function project_streams($a,$b){$l=$this->ledger($a,$b);$p=$this->pair($a,$b);$ab=!empty($l['follow_a_to_b']);$ba=!empty($l['follow_b_to_a']);if($ab)$this->ext_follow_upsert(self::STREAMS,$a,$b,1);else $this->ext_follow_delete(self::STREAMS,$a,$b);if($ba)$this->ext_follow_upsert(self::STREAMS,$b,$a,1);else $this->ext_follow_delete(self::STREAMS,$b,$a);}
    private function project_pair($a,$b){$l=$this->ledger($a,$b);if(!empty($l['block_a_to_b']))$this->ext_block(self::STREAMS,$a,$b,1);else $this->ext_block(self::STREAMS,$a,$b,0);if(!empty($l['block_b_to_a']))$this->ext_block(self::STREAMS,$b,$a,1);else $this->ext_block(self::STREAMS,$b,$a,0);if(!empty($l['block_a_to_b']))$this->ext_follow_delete(self::STREAMS,$a,$b);if(!empty($l['block_b_to_a']))$this->ext_follow_delete(self::STREAMS,$b,$a);$this->project_streams($a,$b);if(!empty($l['block_a_to_b']))$this->ext_block(self::SOCIALS,$a,$b,1);else $this->ext_block(self::SOCIALS,$a,$b,0);if(!empty($l['block_b_to_a']))$this->ext_block(self::SOCIALS,$b,$a,1);else $this->ext_block(self::SOCIALS,$b,$a,0);if(!empty($l['block_a_to_b'])||!empty($l['block_b_to_a'])){try{$this->ext_follow_delete(self::SOCIALS,$a,$b);}catch(Throwable $e){}try{$this->ext_follow_delete(self::SOCIALS,$b,$a);}catch(Throwable $e){}}else $this->project_socials($a,$b);}
    private function enforce_block_bb($a,$b,$uuid){if(function_exists('friends_check_friendship_status')&&function_exists('friends_remove_friend')&&$this->bb_status($a,$b)==='is_friend'){$this->push();try{friends_remove_friend($a,$b);}finally{$this->pop();}}if(function_exists('bp_stop_following')&&function_exists('bp_is_following'))foreach(array(array($a,$b),array($b,$a)) as $d)if(bp_is_following(array('leader_id'=>$d[1],'follower_id'=>$d[0]))){$this->push();try{bp_stop_following(array('leader_id'=>$d[1],'follower_id'=>$d[0]));}finally{$this->pop();}}$this->refresh_ledger($a,$b,$uuid);}
    private function handle_bb_connection($op,$a,$b){if($this->internal()||$a<1||$b<1||$a===$b)return;$uuid=wp_generate_uuid4();if(!$this->lock($a,$b)){$this->create_event($uuid,self::WP,$op,$a,$b);$this->retry($uuid,'pair lock busy');return;}try{$this->create_event($uuid,self::WP,$op,$a,$b);$this->refresh_ledger($a,$b,$uuid);$this->project_pair($a,$b);$this->processed($uuid);}catch(Throwable $e){$this->retry($uuid,$e->getMessage());$this->log('BuddyBoss connection projection failed',array('operation'=>$op,'actor'=>$a,'target'=>$b,'error'=>$e->getMessage()));}finally{$this->unlock($a,$b);}}
    public function bb_requested($id,$i,$f,$friendship=null){$this->handle_bb_connection(self::REQUEST,absint($i),absint($f));}
    public function bb_accepted($id,$i,$f,$friendship=null){$this->handle_bb_connection(self::ACCEPT,absint($i),absint($f));}
    public function bb_rejected($id,$friendship=null){if(!is_object($friendship)&&$id&&class_exists('BP_Friends_Friendship'))$friendship=new BP_Friends_Friendship($id);if(is_object($friendship))$this->handle_bb_connection(self::REJECT,absint($friendship->initiator_user_id),absint($friendship->friend_user_id));}
    public function bb_withdrawn($id,$friendship=null){if(!is_object($friendship)&&$id&&class_exists('BP_Friends_Friendship'))$friendship=new BP_Friends_Friendship($id,true,false);if(is_object($friendship))$this->handle_bb_connection(self::WITHDRAW,absint($friendship->initiator_user_id),absint($friendship->friend_user_id));}
    public function bb_deleted($id,$i,$f){$this->handle_bb_connection(self::REMOVE,absint($i),absint($f));}
    public function bb_post_deleted($i,$f){$this->handle_bb_connection(self::REMOVE,absint($i),absint($f));}
    private function handle_bb_follow($op,$follow){if($this->internal()||!is_object($follow))return;$a=absint(isset($follow->follower_id)?$follow->follower_id:0);$b=absint(isset($follow->leader_id)?$follow->leader_id:0);if($a<1||$b<1||$a===$b)return;$uuid=wp_generate_uuid4();if(!$this->lock($a,$b)){$this->create_event($uuid,self::WP,$op,$a,$b);$this->retry($uuid,'pair lock busy');return;}try{$this->create_event($uuid,self::WP,$op,$a,$b);$this->refresh_ledger($a,$b,$uuid);$this->project_streams($a,$b);$this->processed($uuid);}catch(Throwable $e){$this->retry($uuid,$e->getMessage());$this->log('BuddyBoss follow projection failed',array('operation'=>$op,'actor'=>$a,'target'=>$b,'error'=>$e->getMessage()));}finally{$this->unlock($a,$b);}}
    public function bb_follow_started($f){$this->handle_bb_follow(self::FOLLOW,$f);} public function bb_follow_stopped($f){$this->handle_bb_follow(self::UNFOLLOW,$f);}
    private function is_user_block($m){return is_object($m)&&isset($m->item_type)&&$m->item_type==='user'&&empty($m->user_report)&&absint($m->user_id)>0&&absint($m->item_id)>0;}
    public function bb_moderation_saved($m){if(!$this->is_user_block($m)||$this->internal())return;$a=absint($m->user_id);$b=absint($m->item_id);$uuid=wp_generate_uuid4();if(!$this->lock($a,$b)){ $this->create_event($uuid,self::WP,self::BLOCK,$a,$b,array('moderation_id'=>absint($m->id)));$this->retry($uuid,'pair lock busy');return;}try{$this->create_event($uuid,self::WP,self::BLOCK,$a,$b,array('moderation_id'=>absint($m->id)));$this->push();try{$this->enforce_block_bb($a,$b,$uuid);}finally{$this->pop();}$p=$this->pair($a,$b);$field=$a===$p[0]?'block_a_to_b':'block_b_to_a';$this->save_ledger($a,$b,array($field=>1,'connection_state'=>'none','requested_by'=>0,'follow_a_to_b'=>0,'follow_b_to_a'=>0,'socials_follow_a_to_b'=>0,'socials_follow_b_to_a'=>0),$uuid);$this->project_pair($a,$b);$this->processed($uuid);}catch(Throwable $e){$this->retry($uuid,$e->getMessage());$this->log('BuddyBoss block projection failed',array('actor'=>$a,'target'=>$b,'error'=>$e->getMessage()));}finally{$this->unlock($a,$b);}}
    public function bb_moderation_deleted($m){if(!$this->is_user_block($m)||$this->internal())return;$a=absint($m->user_id);$b=absint($m->item_id);$uuid=wp_generate_uuid4();if(!$this->lock($a,$b)){$this->create_event($uuid,self::WP,self::UNBLOCK,$a,$b);$this->retry($uuid,'pair lock busy');return;}try{$this->create_event($uuid,self::WP,self::UNBLOCK,$a,$b);$p=$this->pair($a,$b);$field=$a===$p[0]?'block_a_to_b':'block_b_to_a';$this->save_ledger($a,$b,array($field=>0),$uuid);$this->refresh_ledger($a,$b,$uuid);$this->project_pair($a,$b);$this->processed($uuid);}catch(Throwable $e){$this->retry($uuid,$e->getMessage());$this->log('BuddyBoss unblock projection failed',array('actor'=>$a,'target'=>$b,'error'=>$e->getMessage()));}finally{$this->unlock($a,$b);}}
    private function secret($origin){$specific=$origin===self::STREAMS?getenv('BZJ_STREAMS_SYNC_SECRET'):getenv('BZJ_SOCIALS_SYNC_SECRET');if($specific)return $specific;if(function_exists('bzj_get_sso_secret')&&($s=bzj_get_sso_secret()))return $s;if(defined('BUZZ_SSO_SECRET')&&BUZZ_SSO_SECRET)return BUZZ_SSO_SECRET;return getenv('BUZZ_SSO_SECRET')?:'';}
    private function authenticate($request,$raw,$origin){$ts=$request->get_header('X-BZJ-Timestamp');$sig=$request->get_header('X-BZJ-Signature');if(!$ts||!$sig||!ctype_digit((string)$ts)||abs(time()-(int)$ts)>self::TIMESTAMP_WINDOW)return new WP_Error('bzj_auth','Invalid or expired synchronization signature',array('status'=>401));$secret=$this->secret($origin);if(!$secret)return new WP_Error('bzj_auth_unavailable','Synchronization secret unavailable',array('status'=>503));$expected=hash_hmac('sha256',(string)((int)$ts).'.'.$raw,$secret);return hash_equals($expected,trim($sig))?true:new WP_Error('bzj_auth_invalid','Invalid synchronization signature',array('status'=>401));}
    private function native_external($origin,$op,$a,$b){
        if($this->bb_blocked($a,$b)&&in_array($op,array(self::REQUEST,self::ACCEPT,self::FOLLOW),true))return new WP_Error('bzj_blocked','Blocked pair cannot create this relationship',array('status'=>409));
        switch($op){
            case self::REQUEST: if(!function_exists('friends_add_friend'))return new WP_Error('bzj_unavailable','BuddyBoss friends unavailable',array('status'=>503));$s=$this->bb_status($a,$b);if($s==='is_friend'||$s==='pending')return true;if($s==='awaiting_response')return new WP_Error('bzj_reverse_request','Reverse pending request exists',array('status'=>409));return friends_add_friend($a,$b)?true:new WP_Error('bzj_request_failed','BuddyBoss rejected connection request',array('status'=>409));
            case self::ACCEPT: if(!function_exists('friends_get_friendship_id')||!function_exists('friends_accept_friendship'))return new WP_Error('bzj_unavailable','BuddyBoss acceptance unavailable',array('status'=>503));$fid=(int)friends_get_friendship_id($b,$a);if(!$fid)$fid=(int)friends_get_friendship_id($a,$b);if(!$fid)return $this->bb_status($a,$b)==='is_friend'?true:new WP_Error('bzj_missing_request','Pending connection not found',array('status'=>409));$r=friends_accept_friendship($fid);return ($r||$this->bb_status($a,$b)==='is_friend')?true:new WP_Error('bzj_accept_failed','BuddyBoss acceptance failed',array('status'=>409));
            case self::REJECT: if(!function_exists('friends_get_friendship_id')||!function_exists('friends_reject_friendship'))return new WP_Error('bzj_unavailable','BuddyBoss rejection unavailable',array('status'=>503));$fid=(int)friends_get_friendship_id($a,$b);if(!$fid)$fid=(int)friends_get_friendship_id($b,$a);if(!$fid)return true;$r=friends_reject_friendship($fid);return ($r||$this->bb_status($a,$b)==='not_friends')?true:new WP_Error('bzj_reject_failed','BuddyBoss rejection failed',array('status'=>409));
            case self::WITHDRAW: if(!function_exists('friends_withdraw_friendship'))return new WP_Error('bzj_unavailable','BuddyBoss withdrawal unavailable',array('status'=>503));$r=friends_withdraw_friendship($a,$b);return ($r||$this->bb_status($a,$b)==='not_friends')?true:new WP_Error('bzj_withdraw_failed','BuddyBoss withdrawal failed',array('status'=>409));
            case self::REMOVE: if(!function_exists('friends_remove_friend'))return new WP_Error('bzj_unavailable','BuddyBoss removal unavailable',array('status'=>503));if($this->bb_status($a,$b)==='is_friend'){if(!friends_remove_friend($a,$b)&&$this->bb_status($a,$b)==='is_friend')return new WP_Error('bzj_remove_failed','BuddyBoss removal failed',array('status'=>409));}return true;
            case self::FOLLOW: if(!function_exists('bp_start_following'))return new WP_Error('bzj_unavailable','BuddyBoss follow unavailable',array('status'=>503));if(function_exists('bp_is_following')&&bp_is_following(array('leader_id'=>$b,'follower_id'=>$a)))return true;$r=bp_start_following(array('leader_id'=>$b,'follower_id'=>$a));return is_wp_error($r)?$r:($r===false?new WP_Error('bzj_follow_failed','BuddyBoss follow failed',array('status'=>409)):true);
            case self::UNFOLLOW: if(!function_exists('bp_stop_following'))return new WP_Error('bzj_unavailable','BuddyBoss unfollow unavailable',array('status'=>503));if(function_exists('bp_is_following')&&!bp_is_following(array('leader_id'=>$b,'follower_id'=>$a)))return true;$r=bp_stop_following(array('leader_id'=>$b,'follower_id'=>$a));return is_wp_error($r)?$r:($r===false&&function_exists('bp_is_following')&&bp_is_following(array('leader_id'=>$b,'follower_id'=>$a))?new WP_Error('bzj_unfollow_failed','BuddyBoss unfollow failed',array('status'=>409)):true);
            case self::BLOCK: if(!class_exists('BP_Moderation')||!class_exists('BP_Moderation_Members'))return new WP_Error('bzj_unavailable','BuddyBoss moderation unavailable',array('status'=>503));$m=new BP_Moderation($b,BP_Moderation_Members::$moderation_type,$a);if(!empty($m->id)&&empty($m->user_report))return true;$m->user_report=0;$m->content='';return $m->save()?true:new WP_Error('bzj_block_failed','BuddyBoss block failed',array('status'=>409));
            case self::UNBLOCK: if(!class_exists('BP_Moderation')||!class_exists('BP_Moderation_Members'))return new WP_Error('bzj_unavailable','BuddyBoss moderation unavailable',array('status'=>503));$m=new BP_Moderation($b,BP_Moderation_Members::$moderation_type,$a);if(empty($m->id)||!empty($m->user_report))return true;return $m->delete(false)?true:new WP_Error('bzj_unblock_failed','BuddyBoss unblock failed',array('status'=>409));
        }
        return new WP_Error('bzj_operation','Unsupported operation',array('status'=>400));
    }
    private function apply_external($origin,$op,$a,$b,$uuid){$result=$this->native_external($origin,$op,$a,$b);if(is_wp_error($result))return $result;
        $this->refresh_ledger($a,$b,$uuid);
        $l=$this->ledger($a,$b);$p=$this->pair($a,$b);
        if($origin===self::SOCIALS&&$op===self::FOLLOW){$field=$a===$p[0]?'socials_follow_a_to_b':'socials_follow_b_to_a';$this->save_ledger($a,$b,array($field=>1),$uuid);}
        if($origin===self::SOCIALS&&$op===self::UNFOLLOW){$field=$a===$p[0]?'socials_follow_a_to_b':'socials_follow_b_to_a';$this->save_ledger($a,$b,array($field=>0),$uuid);}
        $this->project_pair($a,$b);return true;
    }
    public function rest_command(WP_REST_Request $request){$raw=$request->get_body();$p=json_decode($raw,true);if(!is_array($p))return new WP_Error('bzj_json','Malformed JSON',array('status'=>400));$origin=sanitize_key(isset($p['origin'])?$p['origin']:'');$op=sanitize_key(isset($p['operation'])?$p['operation']:'');$event=sanitize_text_field(isset($p['event_id'])?$p['event_id']:'');$ea=absint(isset($p['actor_id'])?$p['actor_id']:0);$et=absint(isset($p['target_id'])?$p['target_id']:0);if(!in_array($origin,array(self::STREAMS,self::SOCIALS),true)||!in_array($op,array(self::REQUEST,self::ACCEPT,self::REJECT,self::WITHDRAW,self::REMOVE,self::FOLLOW,self::UNFOLLOW,self::BLOCK,self::UNBLOCK),true)||!$this->uuid($event)||$ea<1||$et<1||$ea===$et)return new WP_Error('bzj_request','Invalid synchronization command',array('status'=>400));$auth=$this->authenticate($request,$raw,$origin);if(is_wp_error($auth))return $auth;$a=$this->wp_from_external($origin,$ea);$b=$this->wp_from_external($origin,$et);if(!$a||!$b||$a===$b)return new WP_Error('bzj_mapping','External user mapping missing',array('status'=>409));if(isset($p['authenticated_id'])&&absint($p['authenticated_id'])!==$ea)return new WP_Error('bzj_actor','Authenticated actor mismatch',array('status'=>403));if($this->event_exists($event)){return rest_ensure_response(array('success'=>true,'status'=>$this->event_status($event)==='processed'?'already_processed':'accepted','event_id'=>$event,'relationship'=>$this->ledger($a,$b)));}if(!$this->lock($a,$b))return new WP_Error('bzj_busy','Relationship pair is busy',array('status'=>503));try{$this->create_event($event,$origin,$op,$a,$b,$p);$r=$this->apply_external($origin,$op,$a,$b,$event);if(is_wp_error($r)){$this->retry($event,$r->get_error_message());return $r;}$this->processed($event);return rest_ensure_response(array('success'=>true,'status'=>'processed','event_id'=>$event,'relationship'=>$this->ledger($a,$b)));}catch(Throwable $e){$this->retry($event,$e->getMessage());$this->log('REST command failed',array('event_id'=>$event,'origin'=>$origin,'operation'=>$op,'actor'=>$a,'target'=>$b,'error'=>$e->getMessage()));return new WP_Error('bzj_internal','Synchronization failed',array('status'=>500,'event_id'=>$event));}finally{$this->unlock($a,$b);}}
    public function register_routes(){register_rest_route(self::NS,self::ROUTE,array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'rest_command'),'permission_callback'=>'__return_true'));register_rest_route(self::NS,self::ROUTE,array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'rest_status'),'permission_callback'=>function(){return current_user_can('manage_options');}));register_rest_route(self::NS,self::ROUTE.'/diagnostics',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'rest_diagnostics'),'permission_callback'=>function(){return current_user_can('manage_options');}));}
    public function rest_status(WP_REST_Request $r){$a=absint($r->get_param('user_a'));$b=absint($r->get_param('user_b'));if($a<1||$b<1||$a===$b)return new WP_Error('bzj_pair','Two valid different WordPress user IDs are required',array('status'=>400));return rest_ensure_response(array('success'=>true,'version'=>self::VERSION,'relationship'=>$this->ledger($a,$b)));}
    public function rest_diagnostics(){global $wpdb;$this->load_helpers();$s=$this->db(self::STREAMS);$q=$this->db(self::SOCIALS);$st=array();$qt=array();foreach(array('Wo_Followers','Wo_Blocks') as $t)$st[$t]=$s?$this->table($s,self::STREAMS,$t==='Wo_Followers'?'follow':'block'):false;foreach(array('followers','blocks') as $t)$qt[$t]=$q?$this->table($q,self::SOCIALS,$t==='followers'?'follow':'block'):false;$this->log('Diagnostics requested',array('streams_db'=>(bool)$s,'socials_db'=>(bool)$q,'streams_tables'=>$st,'socials_tables'=>$qt));return rest_ensure_response(array('success'=>true,'version'=>self::VERSION,'ledger_table'=>$this->ledger_table,'events_table'=>$this->events_table,'streams_connected'=>(bool)$s,'socials_connected'=>(bool)$q,'streams_tables'=>$st,'socials_tables'=>$qt,'pending_events'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->events_table} WHERE status='pending'"),'failed_events'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM {$this->events_table} WHERE status='failed'"),'log_file'=>trailingslashit(ABSPATH).ltrim(self::LOG_DIR,'/').'/'.self::LOG_FILE));}
    private function recover_one($row){$a=(int)$row->actor_wp_id;$b=(int)$row->target_wp_id;if($a<1||$b<1){$this->retry($row->event_uuid,'Invalid recovery users');return;}if(!$this->lock($a,$b)){return;}global $wpdb;try{$wpdb->update($this->events_table,array('status'=>'processing','updated_at'=>gmdate('Y-m-d H:i:s')),array('event_uuid'=>$row->event_uuid));$payload=json_decode((string)$row->payload,true);$origin=$row->origin;$op=$row->operation;if($origin===self::WP){$this->refresh_ledger($a,$b,$row->event_uuid);$this->project_pair($a,$b);}else{$r=$this->apply_external($origin,$op,$a,$b,$row->event_uuid);if(is_wp_error($r))throw new RuntimeException($r->get_error_message());}$this->processed($row->event_uuid);}catch(Throwable $e){$this->retry($row->event_uuid,$e->getMessage());$this->log('Recovery failed',array('event_id'=>$row->event_uuid,'error'=>$e->getMessage()));}finally{$this->unlock($a,$b);}}
    public function process_recovery(){global $wpdb;$rows=$wpdb->get_results("SELECT * FROM {$this->events_table} WHERE status='pending' AND next_attempt_at<=UTC_TIMESTAMP() ORDER BY id ASC LIMIT 25");foreach((array)$rows as $row)$this->recover_one($row);}
}
BZJ_Connections_Sync::instance();
