<span id="Follow-<?php echo $wo['follow']['user_id']?>">
    <button type="button" onclick="Wo_RegisterFollow(<?php echo (int)$wo['follow']['user_id'];?>)" class="btn btn-default btn-sm wo_follow_btn" id="wo_useract_btn">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M14.75 8.44434H11.75M13.25 9.94434L13.25 6.94434" class="icon_main" stroke-width="1.5" stroke-linecap="round"/>
            <path d="M1.25 13.7779C1.25 11.9681 2.52299 10.4266 4.25303 10.1413L4.40886 10.1413" stroke="currentColor" stroke-width="1.5"/>
        </svg>
        <span class="button-text"> <?php echo $wo['lang']['follow'];?></span>
    </button>
</span>
