<?php
/** BZJ external-platform connection-management client. */
if (!defined('BZJ_CONNECTION_CLIENT_LOADED')) {
define('BZJ_CONNECTION_CLIENT_LOADED', true);
function bzj_connection_uuid(){try{$d=random_bytes(16);}catch(Throwable $e){$d=md5(uniqid('',true),true);} $d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
function bzj_connection_client_secret(){if(function_exists('bzj_get_sso_secret')){$s=bzj_get_sso_secret();if($s)return $s;}if(defined('BUZZ_SSO_SECRET')&&BUZZ_SSO_SECRET)return BUZZ_SSO_SECRET;return getenv('BUZZ_SSO_SECRET')?:'';}
function bzj_connection_client_log($message,$ctx=array()){$dir=dirname(__DIR__).'/data/logs';if(!is_dir($dir))@mkdir($dir,0755,true);@file_put_contents($dir.'/bzj-connections-client.log',json_encode(array('time'=>gmdate('c'),'message'=>$message,'context'=>$ctx),JSON_UNESCAPED_SLASHES).PHP_EOL,FILE_APPEND|LOCK_EX);}
function bzj_connection_client($origin,$operation,$actor_id,$target_id,$extra=array()){$secret=bzj_connection_client_secret();$base=getenv('WORDPRESS_API_BASE')?:'https://buzzjuice.net/wp-json';$url=rtrim($base,'/').'/bzj/v6/connection-management';$payload=array_merge(array('origin'=>$origin,'operation'=>$operation,'actor_id'=>(int)$actor_id,'target_id'=>(int)$target_id,'authenticated_id'=>(int)$actor_id,'event_id'=>bzj_connection_uuid()),$extra);$raw=json_encode($payload,JSON_UNESCAPED_SLASHES);$ts=(string)time();$sig=hash_hmac('sha256',$ts.'.'.$raw,$secret);$ch=curl_init($url);curl_setopt_array($ch,array(CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>array('Content-Type: application/json','X-BZJ-Timestamp: '.$ts,'X-BZJ-Signature: '.$sig),CURLOPT_POSTFIELDS=>$raw));$body=curl_exec($ch);$errno=curl_errno($ch);$error=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$ok=$errno===0&&$code>=200&&$code<300;$result=$body?json_decode($body,true):array();bzj_connection_client_log($ok?'Synchronization request accepted':'Synchronization request failed',array('origin'=>$origin,'operation'=>$operation,'actor'=>$actor_id,'target'=>$target_id,'http_code'=>$code,'curl_errno'=>$errno,'curl_error'=>$error,'response'=>$result));return $ok?$result:false;}
}
